### PR TITLE
create an express skeleton + any fixes that are needed to the main package

### PR DESCRIPTION
**Pull request by HopefulFire**
Hey, so this is going to be the first pull request we merge, if it is approved

### CODE REVIEW

**Comment by HopefulFire** [comment]
The reason there is -38,100 lines of code is that I removed package-lock.json from the git tracker. Normally, this would be done in a separate pull request, but it's a small change and we're just getting started so it's probably best to not overcomplicate things.

**Comment by HopefulFire** [comment]
As this is a draft pull request, it cannot be merged. And, when it leaves draft state, it cannot be merged without a review according to the policies I've set forth.

**Review by tedtke — APPROVED** [review]
awesome possum

**Review by tedtke — APPROVED** [review]
.

**Review by tedtke — APPROVED** [review]
everything looks good

**Pull request merged**
